import { describe, test, expect, beforeAll, afterAll } from 'vitest';
import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import mongoose from 'mongoose';

const API_URL = 'http://localhost:5001/api/candidates';
const UPLOADS_DIR = path.resolve(__dirname, '../../server/uploads');

function createDummyPDF(filePath, text) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument();
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);
    doc.text(text);
    doc.end();
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

async function seedCandidate(id, name, email = '') {
  const Candidate = mongoose.model('Candidate');
  const candidate = new Candidate({
    id,
    name,
    email,
    skills: ['JavaScript'],
    resumeUrl: '/api/uploads/dummy-existing.pdf',
    resumeText: 'Existing Alice resume text',
    experience: [],
    education: [],
    hrQuestions: [],
    technicalQuestions: []
  });
  await candidate.save();
  return candidate;
}

describe('Duplicate Candidate Resolution Backend API', () => {
  const dummyPath = path.resolve(__dirname, './alice_resume.pdf');

  beforeAll(async () => {
    await createDummyPDF(dummyPath, 'Alice\nEmail: alice@example.com\nSkills: JavaScript, Python');
  });

  afterAll(() => {
    if (fs.existsSync(dummyPath)) {
      fs.unlinkSync(dummyPath);
    }
  });

  async function uploadDuplicate(pdfPath) {
    const formData = new FormData();
    const fileBuffer = fs.readFileSync(pdfPath);
    const blob = new Blob([fileBuffer], { type: 'application/pdf' });
    formData.append('resume', blob, 'alice_resume.pdf');

    const res = await fetch(`${API_URL}/upload`, {
      method: 'POST',
      body: formData
    });
    return res;
  }

  test('Seeding a candidate, uploading a duplicate with a name containing "alice" to trigger 409 conflict and set IngestionLog to "duplicate"', async () => {
    const existing = await seedCandidate('candidate-alice', 'Alice', 'alice@example.com');
    
    const uploadRes = await uploadDuplicate(dummyPath);
    expect(uploadRes.status).toBe(409);
    
    const uploadData = await uploadRes.json();
    expect(uploadData.duplicate).toBe(true);
    expect(uploadData.logId).toBeDefined();

    const IngestionLog = mongoose.model('IngestionLog');
    const log = await IngestionLog.findOne({ id: uploadData.logId });
    expect(log).not.toBeNull();
    expect(log.status).toBe('duplicate');

    // Cleanup temp file generated by upload to avoid cluttering
    if (uploadData.tempFile) {
      const tempFilePath = path.join(UPLOADS_DIR, uploadData.tempFile);
      if (fs.existsSync(tempFilePath)) {
        fs.unlinkSync(tempFilePath);
      }
    }
  });

  test('Update Action: resolve with "update" -> verify candidate preserves ID, updates other fields, and IngestionLog status is "success"', async () => {
    const existing = await seedCandidate('candidate-alice', 'Alice', 'alice@example.com');
    
    const uploadRes = await uploadDuplicate(dummyPath);
    expect(uploadRes.status).toBe(409);
    const uploadData = await uploadRes.json();

    const parsedData = uploadData.parsedData || {};
    parsedData.phone = '123-456-7890';
    parsedData.linkedinUrl = 'https://linkedin.com/in/alice-updated';

    const resolveRes = await fetch(`${API_URL}/upload/resolve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'update',
        candidateId: existing.id,
        tempFile: uploadData.tempFile,
        parsedData,
        pdfText: uploadData.pdfText,
        logId: uploadData.logId
      })
    });

    expect(resolveRes.status).toBe(200);
    const resolvedData = await resolveRes.json();
    expect(resolvedData.id).toBe(existing.id);

    const Candidate = mongoose.model('Candidate');
    const dbCandidate = await Candidate.findOne({ id: existing.id });
    expect(dbCandidate).not.toBeNull();
    expect(dbCandidate.phone).toBe('123-456-7890');
    expect(dbCandidate.linkedinUrl).toBe('https://linkedin.com/in/alice-updated');

    const IngestionLog = mongoose.model('IngestionLog');
    const log = await IngestionLog.findOne({ id: uploadData.logId });
    expect(log.status).toBe('success');
  });

  test('Delete & Re-import Action: resolve with "delete-before" -> verify candidate gets a new ID, old candidate deleted, and IngestionLog status is "success"', async () => {
    const existing = await seedCandidate('candidate-alice', 'Alice', 'alice@example.com');
    
    const uploadRes = await uploadDuplicate(dummyPath);
    expect(uploadRes.status).toBe(409);
    const uploadData = await uploadRes.json();

    const resolveRes = await fetch(`${API_URL}/upload/resolve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'delete-before',
        candidateId: existing.id,
        tempFile: uploadData.tempFile,
        parsedData: uploadData.parsedData,
        pdfText: uploadData.pdfText,
        logId: uploadData.logId
      })
    });

    expect(resolveRes.status).toBe(200);
    const resolvedData = await resolveRes.json();
    expect(resolvedData.id).toBeDefined();
    expect(resolvedData.id).not.toBe(existing.id);

    const Candidate = mongoose.model('Candidate');
    const oldCand = await Candidate.findOne({ id: existing.id });
    expect(oldCand).toBeNull();

    const newCand = await Candidate.findOne({ id: resolvedData.id });
    expect(newCand).not.toBeNull();

    const IngestionLog = mongoose.model('IngestionLog');
    const log = await IngestionLog.findOne({ id: uploadData.logId });
    expect(log.status).toBe('success');
  });

  test('Delete Existing Only Action: resolve with "remove" -> verify candidate is deleted, temp file deleted, and IngestionLog status is "cancelled"', async () => {
    const existing = await seedCandidate('candidate-alice', 'Alice', 'alice@example.com');
    
    const uploadRes = await uploadDuplicate(dummyPath);
    expect(uploadRes.status).toBe(409);
    const uploadData = await uploadRes.json();

    const tempFilePath = path.join(UPLOADS_DIR, uploadData.tempFile);
    expect(fs.existsSync(tempFilePath)).toBe(true);

    const resolveRes = await fetch(`${API_URL}/upload/resolve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'remove',
        candidateId: existing.id,
        tempFile: uploadData.tempFile,
        parsedData: uploadData.parsedData,
        pdfText: uploadData.pdfText,
        logId: uploadData.logId
      })
    });

    expect(resolveRes.status).toBe(200);
    const resolvedData = await resolveRes.json();
    expect(resolvedData.success).toBe(true);
    expect(resolvedData.removed).toBe(true);

    const Candidate = mongoose.model('Candidate');
    const dbCandidate = await Candidate.findOne({ id: existing.id });
    expect(dbCandidate).toBeNull();

    // Verify temp file deleted
    expect(fs.existsSync(tempFilePath)).toBe(false);

    const IngestionLog = mongoose.model('IngestionLog');
    const log = await IngestionLog.findOne({ id: uploadData.logId });
    expect(log.status).toBe('cancelled');
  });

  test('Cancel Action: resolve with "cancel" -> verify candidate is unmodified, temp file deleted, and IngestionLog status is "cancelled"', async () => {
    const existing = await seedCandidate('candidate-alice', 'Alice', 'alice@example.com');
    
    const uploadRes = await uploadDuplicate(dummyPath);
    expect(uploadRes.status).toBe(409);
    const uploadData = await uploadRes.json();

    const tempFilePath = path.join(UPLOADS_DIR, uploadData.tempFile);
    expect(fs.existsSync(tempFilePath)).toBe(true);

    const resolveRes = await fetch(`${API_URL}/upload/resolve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'cancel',
        candidateId: existing.id,
        tempFile: uploadData.tempFile,
        parsedData: uploadData.parsedData,
        pdfText: uploadData.pdfText,
        logId: uploadData.logId
      })
    });

    expect(resolveRes.status).toBe(200);
    const resolvedData = await resolveRes.json();
    expect(resolvedData.success).toBe(true);
    expect(resolvedData.cancelled).toBe(true);

    const Candidate = mongoose.model('Candidate');
    const dbCandidate = await Candidate.findOne({ id: existing.id });
    expect(dbCandidate).not.toBeNull();
    expect(dbCandidate.email).toBe('alice@example.com');
    expect(dbCandidate.name).toBe('Alice');

    // Verify temp file deleted
    expect(fs.existsSync(tempFilePath)).toBe(false);

    const IngestionLog = mongoose.model('IngestionLog');
    const log = await IngestionLog.findOne({ id: uploadData.logId });
    expect(log.status).toBe('cancelled');
  });

  test('Failed Log Status (Action validation): resolve with invalid action -> verify 400 Bad Request, IngestionLog status is "failed"', async () => {
    const existing = await seedCandidate('candidate-alice', 'Alice', 'alice@example.com');
    
    const uploadRes = await uploadDuplicate(dummyPath);
    expect(uploadRes.status).toBe(409);
    const uploadData = await uploadRes.json();

    const resolveRes = await fetch(`${API_URL}/upload/resolve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'invalid-action-value',
        candidateId: existing.id,
        tempFile: uploadData.tempFile,
        parsedData: uploadData.parsedData,
        pdfText: uploadData.pdfText,
        logId: uploadData.logId
      })
    });

    expect(resolveRes.status).toBe(400);

    const IngestionLog = mongoose.model('IngestionLog');
    const log = await IngestionLog.findOne({ id: uploadData.logId });
    expect(log.status).toBe('failed');
    expect(log.error).toBe('Invalid action provided.');

    // Cleanup temp file generated by upload to avoid cluttering
    if (uploadData.tempFile) {
      const tempFilePath = path.join(UPLOADS_DIR, uploadData.tempFile);
      if (fs.existsSync(tempFilePath)) {
        fs.unlinkSync(tempFilePath);
      }
    }
  });

  test('Failed Log Status (Missing Candidate): resolve "update" with non-existent candidate ID -> verify 404 response, IngestionLog status is "failed"', async () => {
    const existing = await seedCandidate('candidate-alice', 'Alice', 'alice@example.com');
    
    const uploadRes = await uploadDuplicate(dummyPath);
    expect(uploadRes.status).toBe(409);
    const uploadData = await uploadRes.json();

    const resolveRes = await fetch(`${API_URL}/upload/resolve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'update',
        candidateId: 'non-existent-id',
        tempFile: uploadData.tempFile,
        parsedData: uploadData.parsedData,
        pdfText: uploadData.pdfText,
        logId: uploadData.logId
      })
    });

    expect(resolveRes.status).toBe(404);

    const IngestionLog = mongoose.model('IngestionLog');
    const log = await IngestionLog.findOne({ id: uploadData.logId });
    expect(log.status).toBe('failed');
    expect(log.error).toBe('Candidate not found.');

    // Verify temp file deleted
    const tempFilePath = path.join(UPLOADS_DIR, uploadData.tempFile);
    expect(fs.existsSync(tempFilePath)).toBe(false);
  });

  test('Test 8: Edge Case - Path Traversal Prevention: Send resolve request with traversal tempFile path -> verify 400 Bad Request', async () => {
    const existing = await seedCandidate('candidate-alice', 'Alice', 'alice@example.com');

    const resolveRes = await fetch(`${API_URL}/upload/resolve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'update',
        candidateId: existing.id,
        tempFile: '../../package.json',
        parsedData: { name: 'Alice', email: 'alice@example.com' },
        pdfText: 'some text',
        logId: 'dummy-log-id'
      })
    });

    expect(resolveRes.status).toBe(400);
    const resData = await resolveRes.json();
    expect(resData.error).toBe('Invalid tempFile path.');
  });
});
